#
# Iman Sjamhudi +628999175163 indoomni@gmail.com
#

# Select image from https://hub.docker.com/_/php/
image: php:7.0-apache

# Select what we should cache between builds
cache:
  paths:
  - vendor/

stages:
  - test
  - build
  - deploy

before_script:
- uname -a
- pwd
- cp /srv/Oyes_New/oyes_api/.env .
- docker info
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

test:
  stage: test
  tags:
    - test
  script: echo "Running tests"

build:
  stage: build
  tags:
    - build
  script:
    - echo "Building the app"
    - docker-compose build
    - docker-compose push
#     - docker push $CI_REGISTRY_IMAGE:latest

# deploy_review:
#   stage: deploy
#   script:
#     - echo "Deploy a review app"
#   environment:
#     name: review/$CI_COMMIT_REF_NAME
#     url: https://$CI_ENVIRONMENT_SLUG.example.com
#     on_stop: stop_review
#   only:
#     - branches
#   except:
#     - master

# stop_review:
#   stage: deploy
#   variables:
#     GIT_STRATEGY: none
#   script:
#     - echo "Remove review app"
#   when: manual
#   environment:
#     name: review/$CI_COMMIT_REF_NAME
#     action: stop

deploy_staging:
  stage: deploy
  tags:
    - staging
  script:
    - echo "Deploy to staging server"
    - docker-compose pull
    - docker-compose down
    - docker-compose up -d
  environment:
    name: staging
    url: http://dev-api.oyes.id
  only:
  - master

deploy_production:
  stage: deploy
  tags:
    - production
  script:
    - echo "Deploy to production server"
    - docker-compose pull
    - docker-compose down
    - docker-compose up --build -d
  environment:
    name: production
    url: https://api.oyes.id
  when: manual
  only:
  - master